plugins {
    id "com.android.application"
}

def signingPropertiesFile = rootProject.file("keystore.properties")
def signingProperties = new Properties()
if (signingPropertiesFile.exists()) {
    signingProperties.load(new FileInputStream(signingPropertiesFile))
}

android {
    namespace "app.weijin.notes"
    compileSdk 35

    defaultConfig {
        applicationId "app.weijin.notes"
        minSdk 33
        targetSdk 35
          versionCode 36
          versionName "4.6"
    }

    signingConfigs {
        release {
            if (signingPropertiesFile.exists()) {
                storeFile rootProject.file(signingProperties["storeFile"])
                storePassword signingProperties["storePassword"]
                keyAlias signingProperties["keyAlias"]
                keyPassword signingProperties["keyPassword"]
            }
        }
    }

    buildTypes {
        release {
            if (signingPropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.core:core-splashscreen:1.0.1"
}
